using System.Collections.Generic;

namespace Symulation
{
    public class Pod
    {
       

        public enum MovmentStateOfPod
        {
            Stationary,
            EnRoute
        }

        public Pod(int PodNumer, CityDataStorage city)
        {
            Numer = PodNumer;
            
        }

        

        public int Numer { get; }


        



        // two elementary operations on pod city map
        // those two are used by mod class to compose
        // more comlicated modifications
        

    }

    public class CityMod
    {

        //current rules for modifications 
            // only one mod can affect given section of city
            // mods are listed and described in such a way that it is easy to remove mod if needed
                // what description is needed to easyly remove mod if needed 
                // there have to be special metod which can remove mod if need, per stored description 
            // moda are assigned to city section
            // when mod is beeing changed, old mod is removed and new one is applied


        // there will be description of mod here
            // generated by section of city number
            
        // Mod by given section is composed of elementary mods
        // parametrised to deffine 

        public void SortingMod(CityDataStorage cityData)
        {
            //marker for going left or right, needed during animation 





        }



    }

    public class ManagementOfCityMods: CityMod
    {



        //method: mode city
        //add if there is no mod by given section 
        //modiffy if there mod is allready defined


        //method: restore city to base state

        //method: perform all mods on route

        //method: search if mod by section number"  " is already defined 


        //types of modes
        //mode for sorting section v1.0

            // higher level where sorting section input is defined, numbers of pods and directions
                    //number of pods, and 
            // based on number of pods and directions, needed move is calculated
            // based on that move, for each pod sorting mode is calculated
                    //move is defined by start point and end point plus change in speed 

        //mode for ...
        //problem: how to describe mods for sections with complicated shapes
        //should there be a object describing section , with defined elementary mods and parameters needed to apply mod: sounds good
       
        


    }

}
